In [1]:
%load_ext sql

In [2]:
%sql sqlite:///../data/nba.sqlite

In [13]:
%config SqlMagic.style = '_DEPRECATED_DEFAULT'

In [14]:
%%sql
PRAGMA database_list;

 * sqlite:///../data/nba.sqlite
Done.

[(0, 'main', '/nba-data/data/nba.sqlite')]

In [15]:
%%sql
SELECT name FROM sqlite_master WHERE type='table';

 * sqlite:///../data/nba.sqlite
Done.

[('game',),
 ('game_summary',),
 ('other_stats',),
 ('officials',),
 ('inactive_players',),
 ('game_info',),
 ('line_score',),
 ('play_by_play',),
 ('player',),
 ('team',),
 ('common_player_info',),
 ('team_details',),
 ('team_history',),
 ('draft_combine_stats',),
 ('draft_history',),
 ('team_info_common',)]

In [24]:
%%sql
SELECT COUNT(*) as teams_quantity from team;

 * sqlite:///../data/nba.sqlite
Done.

[(30,)]

In [26]:
%%sql
SELECT * from team;

 * sqlite:///../data/nba.sqlite
Done.

[('1610612737', 'Atlanta Hawks', 'ATL', 'Hawks', 'Atlanta', 'Georgia', 1949.0),
 ('1610612738', 'Boston Celtics', 'BOS', 'Celtics', 'Boston', 'Massachusetts', 1946.0),
 ('1610612739', 'Cleveland Cavaliers', 'CLE', 'Cavaliers', 'Cleveland', 'Ohio', 1970.0),
 ('1610612740', 'New Orleans Pelicans', 'NOP', 'Pelicans', 'New Orleans', 'Louisiana', 2002.0),
 ('1610612741', 'Chicago Bulls', 'CHI', 'Bulls', 'Chicago', 'Illinois', 1966.0),
 ('1610612742', 'Dallas Mavericks', 'DAL', 'Mavericks', 'Dallas', 'Texas', 1980.0),
 ('1610612743', 'Denver Nuggets', 'DEN', 'Nuggets', 'Denver', 'Colorado', 1976.0),
 ('1610612744', 'Golden State Warriors', 'GSW', 'Warriors', 'Golden State', 'California', 1946.0),
 ('1610612745', 'Houston Rockets', 'HOU', 'Rockets', 'Houston', 'Texas', 1967.0),
 ('1610612746', 'Los Angeles Clippers', 'LAC', 'Clippers', 'Los Angeles', 'California', 1970.0),
 ('1610612747', 'Los Angeles Lakers', 'LAL', 'Lakers', 'Los Angeles', 'California', 1948.0),
 ('1610612748', 'Miami Heat', 'MIA', 'Heat', 'Miami', 'Florida', 1988.0),
 ('1610612749', 'Milwaukee Bucks', 'MIL', 'Bucks', 'Milwaukee', 'Wisconsin', 1968.0),
 ('1610612750', 'Minnesota Timberwolves', 'MIN', 'Timberwolves', 'Minnesota', 'Minnesota', 1989.0),
 ('1610612751', 'Brooklyn Nets', 'BKN', 'Nets', 'Brooklyn', 'New York', 1976.0),
 ('1610612752', 'New York Knicks', 'NYK', 'Knicks', 'New York', 'New York', 1946.0),
 ('1610612753', 'Orlando Magic', 'ORL', 'Magic', 'Orlando', 'Florida', 1989.0),
 ('1610612754', 'Indiana Pacers', 'IND', 'Pacers', 'Indiana', 'Indiana', 1976.0),
 ('1610612755', 'Philadelphia 76ers', 'PHI', '76ers', 'Philadelphia', 'Pennsylvania', 1949.0),
 ('1610612756', 'Phoenix Suns', 'PHX', 'Suns', 'Phoenix', 'Arizona', 1968.0),
 ('1610612757', 'Portland Trail Blazers', 'POR', 'Trail Blazers', 'Portland', 'Oregon', 1970.0),
 ('1610612758', 'Sacramento Kings', 'SAC', 'Kings', 'Sacramento', 'California', 1948.0),
 ('1610612759', 'San Antonio Spurs', 'SAS', 'Spurs', 'San Antonio', 'Texas', 1976.0),
 ('1610612760', 'Oklahoma City Thunder', 'OKC', 'Thunder', 'Oklahoma City', 'Oklahoma', 1967.0),
 ('1610612761', 'Toronto Raptors', 'TOR', 'Raptors', 'Toronto', 'Ontario', 1995.0),
 ('1610612762', 'Utah Jazz', 'UTA', 'Jazz', 'Utah', 'Utah', 1974.0),
 ('1610612763', 'Memphis Grizzlies', 'MEM', 'Grizzlies', 'Memphis', 'Tennessee', 1995.0),
 ('1610612764', 'Washington Wizards', 'WAS', 'Wizards', 'Washington', 'District of Columbia', 1961.0),
 ('1610612765', 'Detroit Pistons', 'DET', 'Pistons', 'Detroit', 'Michigan', 1948.0),
 ('1610612766', 'Charlotte Hornets', 'CHA', 'Hornets', 'Charlotte', 'North Carolina', 1988.0)]